version: '3'
services:
  dev:
    image: localhost/python-dev:latest
    container_name: python_dev
    restart: on-failure
    ports:
      - "127.0.0.1:8888:8888"
    volumes:
      - "~/rsync/programming:/home/dev/programming:z"
